<a href="https://colab.research.google.com/github/samarkinav/RF-vs-GB/blob/main/sklearn_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from sklearn import model_selection, datasets

In [26]:
iris = datasets.load_iris()

In [27]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split\
(iris.data, iris.target, test_size=0.3)

In [28]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'\
      .format(len(train_data), len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [29]:
print('Обучающая выборка:\n', train_data[:5])
print('\n')
print('Тестовая выборка:\n', test_data[:5])

Обучающая выборка:
 [[4.9 3.1 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [5.5 2.6 4.4 1.2]
 [6.8 3.2 5.9 2.3]
 [5.1 3.3 1.7 0.5]]


Тестовая выборка:
 [[5.4 3.4 1.5 0.4]
 [4.8 3.4 1.9 0.2]
 [6.  2.7 5.1 1.6]
 [7.3 2.9 6.3 1.8]
 [5.8 2.7 3.9 1.2]]


In [30]:
print('Метки классов на обучающей выборке:\n', train_labels)
print('\n')
print('Метки классов на тестовой выборке:\n', test_labels)

Метки классов на обучающей выборке:
 [0 1 1 2 0 2 0 0 2 0 0 2 1 1 1 1 2 2 0 2 0 2 0 1 0 1 0 0 0 0 0 2 1 1 0 1 1
 2 2 2 2 2 0 2 0 1 2 0 0 2 2 1 0 2 2 1 1 2 2 1 0 0 2 1 1 0 2 1 2 0 1 0 2 1
 1 2 2 0 1 1 1 0 2 1 0 0 0 1 1 2 1 0 1 1 1 0 2 0 0 1 2 0 0 2 0]


Метки классов на тестовой выборке:
 [0 0 1 2 1 1 0 2 1 2 0 2 1 0 2 1 0 0 1 2 2 2 1 2 2 2 1 2 0 0 1 0 2 2 1 1 2
 1 0 2 1 2 1 0 1]


## Стратегия проведения кросс-валидации

In [34]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,10)

KFold

In [35]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
  print(train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [36]:
kf = model_selection.KFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in kf.split(X):
  print(train_indices, test_indices)

[0 1 3 7 9] [2 4 5 6 8]
[2 4 5 6 8] [0 1 3 7 9]


In [37]:
kf = model_selection.KFold(n_splits = 2, shuffle = True, random_state = 1)
for train_indices, test_indices in kf.split(X):
  print(train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

В данном случае мы сохраняем соотношение классов в обучающих и тестовых подвыборках. Для того чтобы запустить такую функцию, нам нужно передать ей не только количество объектов, но и непосредственно метки классов на объектах, так как разбиение происходит с учетом меток.

In [38]:
y = np.array([0] * 5 + [1] * 5)
print(y)

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in skf.split(X, y):
  print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 6 8 9] [0 1 2 5 7]
[0 1 2 5 7] [3 4 6 8 9]


In [39]:
target = np.array([0, 1] * 5)
print(target)

skf = model_selection.StratifiedKFold(n_splits = 2,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
  print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[0 1 2 3 5] [4 6 7 8 9]
[4 6 7 8 9] [0 1 2 3 5]


#### ShuffleSplit

Стратегия позволяет строить так называемые случайные перестановки. Таким образом мы можем получить очень много выборок, при этом мы можем специфицировать размер обучающей выборки, и у нас нет никаких ограничений на то, сколько раз каждый объект должен появиться в обучении или в тесте. Каждый раз мы действуем с возвращением, то есть мы получаем одно разбиение и дальше можем строить другое независимо от предыдущего. В качестве аргументов функции нужно указать количество наших объектов, сколько итераций мы хотим и размер тестовой выборки. Вот давайте разобъем данные в соотношении: 80 % — обучение и 20 % — тест, и посмотрим, как будут выглядеть наши выборки.

In [40]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
  print(train_indices, test_indices)

[2 6 8 4 9 5 0 3] [1 7]
[8 2 4 6 1 7 9 5] [3 0]
[4 0 3 1 5 2 8 9] [6 7]
[5 0 2 4 1 6 3 9] [8 7]
[6 8 0 5 9 1 3 4] [2 7]
[8 3 6 1 4 9 2 0] [5 7]
[2 8 1 7 3 0 4 6] [9 5]
[8 1 3 6 5 2 7 9] [4 0]
[4 9 8 3 1 0 7 2] [5 6]
[3 2 7 4 0 6 5 1] [9 8]


#### StratifiedShuffleSplit

В этом случае мы тоже будем получать выборки, которые имеют исходное соотношение классов. Опять же, для этого нам придется передать target и целевую метку в функцию.

In [41]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
  print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 7 9 5 6 2 1 0] [8 4]
[7 6 4 5 2 3 9 0] [8 1]
[1 7 5 4 2 8 0 9] [3 6]
[5 2 4 8 1 7 6 3] [0 9]


#### Leave-One-Out

Это стратегия, которая позволяет оставить каждый объект в тесте 1 раз. Таким образом, тестовая выборка всегда состоит из одного объекта, и каждый объект из нашего набора данных 1 раз присутствует в тесте. Это очень удобная стратегия кросс-валидации, которую хорошо использовать в случае, когда мы имеем небольшую выборку данных. 

In [42]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
  print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
